module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Crystal',
    'Majestic',
    'Golden',
    'Silver',
    'Serene',
    'Shadow',
    'Hidden',
    'Whispering',
    'Thunder',
    'Moonlit',
    'Emerald',
    'Ivory',
    'Blazing'
];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Ridge',
    'Meadow',
    'Peak',
    'Valley',
    'Gorge',
    'Highlands',
    'Trail',
    'Terrace',
    'Lake',
    'Falls',
    'Glen'
];